import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Testimonial from "../components/Home/Testimonial";
import AssociatedBrands from "../components/Home/AssociatedBrands";
import Categories from "../components/Home/Categories";
import Story from "../components/Home/Story";
import Hero from "../components/Home/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Categories />
      <Story />
      <AssociatedBrands />
      <Testimonial />
    </div>
  );
}
